tasks:
  clone-additional-repos:
    name: Clone Additional Repos
    triggeredBy:
      - postDevcontainerStart
    command: |
      IFS=';' read -ra REPOS <<< "$MY_ADDITIONAL_REPOS"
      for repo in "${REPOS[@]}"; do
        [ -z "$repo" ] && continue
        name=$(basename "$repo" .git)
        [ -d "/workspaces/$name" ] || git clone "$repo" "/workspaces/$name"
      done
